zestpkg/event/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField, IntegerField, SelectField, RadioField, TextField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError, Optional
from flask_wtf.file import FileField, FileAllowed
from zestpkg.models import Event, User
from wtforms.widgets import TextArea

class EventForm(FlaskForm):
	title = StringField('Event Title', validators=[DataRequired()])	
	orguname = StringField('Organizer Username', validators=[DataRequired()])
	category = SelectField('Category', validators=[DataRequired(), Optional()], choices=[('zestopen', 'Zest Open'), ('zestclose', 'Zest Close'),('aamod', 'Aamod')])
	subcategory = SelectField('Sub Category', validators=[DataRequired(),Optional()], choices=[('sports', 'Sports'), ('atheletics', 'Atheletics'),('dance', 'Dance'),('drama','Drama'),('music','Music'),('informals','Informals'),('deco', 'Decoration'),('fine arts', 'Fine Arts'), ('literary','Literary'), ('renaissance','Renaissance')])
	image = FileField('Cover Picture', validators=[FileAllowed(['jpg', 'png', 'jpeg'])])
	num_of_member = IntegerField('Number of member',validators=[DataRequired()])
	time = StringField('Event Time')
	about = StringField('Event Details', widget=TextArea())
	status = SelectField('Status', validators=[DataRequired(), Optional()], choices=[('T', 'Online'), ('F', 'Offline')])
	submit = SubmitField('Register Event')

	def validate_orguname(self, orguname):
		user = User.query.filter_by(username=orguname.data).first()
		if user is None:
			raise ValidationError("No account with this username")	

zestpkg/admin/routes.py
from flask import Blueprint, render_template, flash, request, redirect, url_for, current_app, abort
from zestpkg.users.forms import LoginForm, RequestResetForm, ResetPasswordForm
from flask_login import current_user, login_user, logout_user, login_required
from zestpkg import bcrypt, db
from zestpkg.models import *
from zestpkg.event.utils import *
from zestpkg.admin.utils import AdminCheck
from zestpkg.users.forms import RegisterForm
from zestpkg.event.forms import EventForm
from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
from math import ceil


admin = Blueprint('admin', __name__)

#only admin related

@admin.route('/admin', methods=['GET', 'POST'])
@admin.route('/admin/', methods=['GET', 'POST'])
@login_required
def AdminPannel():
	AdminCheck()
	number = {}
	number['user'] = db.session.query(User).count()
	number['event'] = db.session.query(Event).count()
	number['team'] = db.session.query(Team).count()
	number['contestant'] = db.session.query(Contestant).count()

	return render_template('AdminPannel.html', title='AdminPannel', **number)


'''
	 Admin User related
'''

@admin.route('/admin/users', methods=['GET', 'POST'])
@login_required
def AdminUsers():
	AdminCheck()
	page = request.args.get('page', 1, type=int)
	query = request.args.get('q')
	if query != None:
		users = User.query.filter(User.username.like('%' + query + '%')).paginate(page=page, per_page=10)
	else:
		users = User.query.paginate(page=page ,per_page=20)
	last = ceil(users.total/20)	
	return render_template('AdminUsers.html', title='User View', users=users, last_page=last)


@admin.route('/admin/usercreation', methods=['GET', 'POST'])
@login_required
def UserCreation():
	AdminCheck()
	form = RegisterForm()
	if form.validate_on_submit():	
		hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
		user = User(username=form.username.data, email=form.email.data, password=hashed_password)
		db.session.add(user)
		db.session.commit()
		flash("Account has been created for "+form.email.data, category='success')
		return redirect(url_for('admin.UserCreation'))
	return render_template('register.html', title='Admin user registeration', form=form)


@admin.route('/admin/user/<int:uid>/delete')
@login_required
def delete_account(uid):
	AdminCheck()
	user = User.query.get(uid)
	username = user.username
	profile = Profile.query.filter_by(user_id=uid).first()
	contestants = Contestant.query.filter_by(user_id=uid)
	events = Event.query.filter_by(user_id=uid)

	if user != None:
		db.session.delete(user)

	if profile != None:
		db.session.delete(profile)

	if contestants != None:
		for contestant in contestants:
			db.session.delete(contestant)

	if events != None:
		for event in events:
			event.user_id = 1

	db.session.commit()

	flash(f'{username} account has been been deleted!', category='success')
	return redirect(url_for('admin.AdminUsers'))


'''
admin event related
'''


@admin.route('/admin/events')
@login_required
def AdminEvents():
	AdminCheck()
	query = request.args.get('q')
	page = request.args.get('page', 1, type=int)
	if query != None:
		events = Event.query.filter(Event.title.like('%' + query + '%')).paginate(page=page, per_page=10)
	else:
		events = Event.query.paginate(page=page ,per_page=10)

	last = ceil(events.total/10)
	return render_template('AdminEvents.html', title='Events View', events=events, last_page=last)


@admin.route('/admin/event/add', methods=['GET', 'POST'])
@login_required
def add_event():
	AdminCheck()
	if current_user.getProfile() == None:
		flash('Create your profile first', category='info')
		return redirect(url_for('profile.create_profile'))

	form = EventForm()
	if form.validate_on_submit():
		user = User.query.filter_by(username=form.orguname.data).first()
		if user is not None:
			oid = user.id
		else:
			flash('Event form validate orguname filter not working', category='danger')
			abort(500)

		if form.image.data:
			picture = save_picture(form.image.data)
		else:
			picture = "default.jpg"
		try:	
			if form.status.data == 'T':
				form.status.data = True
			else:
				form.status.data = False

			event = Event(title=form.title.data, category=form.category.data, subcategory=form.subcategory.data ,image=picture, user_id=oid, team_limit=form.num_of_member.data, about=form.about.data, status=form.status.data)
			db.session.add(event)
			db.session.commit()
			flash('Your Event Registered Successfully!', 'success')
			return redirect('/')
		except:
			flash('Something went wrong into database', 'danger')
			abort(403)

	return render_template('addevent.html', form=form, title='Register Event')


@admin.route('/admin/event/<int:eid>/update', methods=['GET', 'POST'])
@login_required
def update_event(eid):
	AdminCheck()
	event = Event.query.get_or_404(eid)
	form = EventForm()
	if form.validate_on_submit():
		if form.image.data:
			event.image = save_picture(form.image.data)
		user=User.query.filter_by(username=form.orguname.data).first()		
		
		event.title = form.title.data
		event.user_id=user.id
		event.team_limit = form.num_of_member.data
		event.category = form.category.data
		event.subcategory = form.subcategory.data
		event.time = form.time.data
		event.about = form.about.data
		if form.status.data == 'T':
			event.status = True
		else:
			event.status = False

		db.session.commit()
		flash('Your event is updated!', category='success')
		return redirect(url_for('event.event_page', eid=eid))

	elif request.method == 'GET':
		form.title.data = event.title
		form.orguname.data = event.getOrganizer().username
		form.num_of_member.data = event.team_limit
		form.category.data = event.category
		form.time.data = event.time
		form.subcategory.data = event.subcategory
		form.about.data = event.about
		if event.status == True:
			form.status.data = 'T'
		else:
			form.status.data = 'F'

	return render_template('addevent.html', form=form, title='Update Event')



@admin.route('/admin/event/<int:eid>/delete')
@login_required
def delete_event(eid):
	AdminCheck()
	event = Event.query.get_or_404(eid)
	db.session.delete(event)
	db.session.commit()
	flash('Your event has been deleted', category='success')
	return redirect(url_for('event.all_events'))



@admin.route('/admin/verify/<string:username>/', methods=['GET', 'POST'])
@login_required
def toggleVerfiy(username):
	AdminCheck()
	user = User.query.filter_by(username=username).first()
	if user.verified:
		user.verified = False
	else:
		user.verified = True

	db.session.commit()
	
	return redirect(url_for('admin.AdminUsers'))


'''
Admin Team related
'''
@admin.route('/admin/teams')
@login_required
def AdminTeams():
	page = request.args.get('page', 1, type=int)
	teams = Team.query.paginate(page=page ,per_page=10)
	last = ceil(teams.total/10)
	return render_template('AdminTeams.html', title='Team View', teams=teams, last_page=last)



@admin.route('/admin/contestants')
@login_required
def AdminContestants():
	page = request.args.get('page', 1, type=int)
	contestants = Contestant.query.paginate(page=page ,per_page=10)
	last = ceil(contestants.total/10)
	return render_template('AdminContestants.html', title='Contestants View', contestants=contestants, last_page=last)

zestpkg/contestant/routes.py
from flask import Blueprint, render_template, redirect, flash, request, redirect, url_for
from zestpkg import db
from zestpkg.models import User, Event, Contestant, Team
from flask_login import login_required, current_user

contestant = Blueprint('contestant', __name__)

@contestant.route('/event/<int:eid>/participate')
@login_required
def participate(eid):
	if current_user.profile == None:
		flash('You need to create your Profile Card first!', category='warning')
		return redirect(url_for('profile.create_profile'))

	event = Event.query.get_or_404(eid)

	if len(current_user.participations) > 4:
		flash("Limit Reached - You are already in 5 events, can't register for more!", category='info')
		return redirect(url_for('event.my_events'))

	if event.status == False:
		flash("Registeration for this event is closed right now.", category='warning')
		return redirect(url_for('event.event_page', eid=eid))

	user_gender = current_user.profile.gender
	if event.gender != None and event.gender != user_gender:
		if event.gender == "M":
			flash('This event is only for Boys, check your profile', category="info")
		else:
			flash('This event is only for Girls, check your profile', category="info")
			
		return redirect(url_for('event.event_page', eid=event.id))

	
	con = Contestant.query.filter_by(user_id=current_user.id, event_id=eid).first()
	if con == None:
		p = Contestant(user_id=current_user.id, event_id=eid)
		db.session.add(p)
		db.session.commit()

		flash(f'You are registered for {event.title} event', category='success')
	else:
		flash(f'You are already regsitered for {event.title} event', category='info')

	return redirect(url_for('event.my_events'))




@contestant.route('/events/<int:eid>/withdraw')
@login_required
def withdraw(eid):
	if current_user.getProfile() == None:
		flash('You need to create your Profile Card first!', category='info')
		return redirect(url_for('profile.create_profile'))

	event = Event.query.get_or_404(eid)
	if event.status == False:
		flash("You can't withdraw now! This event is offline right now.", category='warning')
		return redirect(url_for('event.event_page', eid=eid))
	
	x = Contestant.query.filter_by(user_id=current_user.id, event_id=eid).first()

	if x != None:
		if event.eventType() != 'Solo':
			team = Team.query.get(x.team_id)
			if team == None:
				flash("Unexpected error", category='danger')
				abort(500)

			if len(team.members) == 1:
				db.session.delete(team)

		db.session.delete(x)
		db.session.commit()
		
		flash(f'You are removed from {event.title} event', category='info')
	else:
		flash(f'You are already not in {event.title}', category='info')

	return redirect(url_for('event.all_events'))

zestpkg/event/routes.py
import getpass
from flask import Blueprint, render_template, redirect, flash, request, abort, url_for
from flask_login import current_user, login_required
from zestpkg.event.forms import EventForm
from zestpkg import db
from zestpkg.models import Event, Profile, Team, Contestant
from zestpkg.event.utils import *
from math import ceil

event = Blueprint('event', __name__)

@event.route('/events/', methods=['GET'])
def all_events():
	page = request.args.get('page', 1, type=int)
	pagelimit = 7
	cat = ''
	active = ['','','','']
	query = request.args.get('q')
	if query != None:
		title = "Search results for '" + query + "'"
		events = Event.query.filter(Event.title.like('%' + query + '%')).paginate(page=page, per_page=10)

	else:
		category = request.args.get('cat')
		subcat = request.args.get('subcat')
		events = Event.query.paginate(page=page, per_page=pagelimit)
		cat = ''
		title = 'All Zest Events'

		if category == 'aamod':
			active[3] = 'active'
			title = 'Aamod Events'
			cat = 'aamod'
			events = Event.query.filter_by(category='aamod').paginate(page=page, per_page=10)

		elif category == 'zestopen':
			active[1] = 'active'
			title = 'Zest Open'
			cat = 'zestopen'
			events = Event.query.filter_by(category='zestopen').paginate(page=page, per_page=10)
			
		elif category == 'zestclose':
			active[2] = 'active'
			title = 'Zest Close'
			cat = 'zestclose'
			events = Event.query.filter_by(category='zestclose').paginate(page=page, per_page=10)

		if subcat != None:
			title = subcat.capitalize() + ' Events'
			events = Event.query.filter_by(subcategory=subcat).paginate(page=page, per_page=15)

		if events == None:
			cat = ''
			flash('No events in your filter', category='info')
			title = 'All Zest Events'
			events = Event.query.paginate(page=page, per_page=pagelimit)

		if 'active' not in active:
			active[0] = 'active'

	last = ceil(events.total/pagelimit)
	
	return render_template('all_events.html', events=events, title=title, active=active, last_page=last, cat=cat)



@event.route('/event/<int:eid>')
def event_page(eid):
	event = Event.query.get_or_404(eid)
	title = event.title
	profile = Profile.query.filter_by(user_id=event.getOrganizer().id).first()
	notreg = True
	if current_user.is_authenticated:
		x = Contestant.query.filter_by(user_id=current_user.id, event_id=event.id).first()
		if x:
			notreg = False

	return render_template('eventpage.html', event=event, rules=event.rules, user=profile, notreg=notreg, title=title)


@event.route('/event/my', methods=['GET', 'POST'])
@login_required
def my_events():
	return render_template('myevents.html', participations=current_user.participations, title="My Events")



@event.route('/event/<string:eid>/participants')
@login_required
def participant_list(eid):
	event = Event.query.get_or_404(eid)
	if event.eventType() == 'Solo':
		contestants = event.getParticipants()
		return render_template('participants.html', contestants=contestants, event=event)
	else:
		teams = event.getParticipants()
		print(teams)
		return render_template('teamlist.html', teams=teams, event=event)



@event.route('/event/<string:eid>/generate_sheet')
@login_required
def generate_excel(eid):
	if current_user.verified != True:
		flash("Your account is not verified", category='warning')
		abort(500)


	event = Event.query.get_or_404(eid)
	if event.eventType() == 'Solo':
		fileName = "/home/"+ getpass.getuser() +"/zest-website/zestpkg/static/sheets/"+event.title.upper() + "-" + str(event.id) + ".csv"
		print(fileName)
		niggas = event.getParticipants()
		sheet = generate_sheet_solo(fileName, niggas)

	return redirect(url_for('static', filename='sheets/'+event.title.upper() + "-" + str(event.id) + ".xlsx"))

zestpkg/main/routes.py
from datetime import datetime
from flask import Blueprint, render_template, jsonify, request
from shutil import copy
from zestpkg import db
from zestpkg.models import *
from flask_login import login_required
from zestpkg.main.forms import PIDSearch

main = Blueprint('main', __name__)

@main.route('/')
@main.route('/home')
def home():
	return render_template('home.html', title='home')


@main.route('/stats', methods=['GET', 'POST'])
def stats():
	return render_template('stats.html', title='Statistics')

@main.route('/faq')
def faq():
	return render_template('faq.html', title='FAQ')


@main.route('/backup')
@login_required
def backup():
	copy('zestpkg/site.db','zestpkg/static/backup')
	return "<h2>Last backup: " + str(datetime.now()) + "</h2>"


@main.route('/account/<int:pid>')
def pid_detail(pid):
	user = User.query.get(pid)
	if user==None:
		return "<h1>No PID found</h1>"

	return render_template('pid_pass.html',user=user, contestants=user.participations, title='PID Pass')


@main.route('/getinfo', methods=['POST', 'GET'])
def getinfo():
	form = PIDSearch()
	pid = None
	if form.validate_on_submit():
		pid = form.pid.data
		user = User.query.get(pid)
		if user == None:
			flash('Form Validation for PID failed, call admin now!', category='danger')
			abort(403)

	return render_template('getinfo.html', title='PID Pass', form=form, pid=pid)

zestpkg/templates/AdminEvents.html
{% extends 'layout.html' %}
{% block content %}
<div class="col-12">

  <div class="text-center mt-4 animated bounceInDown">
    <h2>Events</h2>
    <hr>
  </div>
  <div class="row justify-content-center m-3 p-3">
    <form action="" method="GET">
      <div class="input-group m-3">
        <div class="input-group-prepend">
          <button class="btn btn-outline-secondary dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Filter by</button>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="/events/?subcat=sports">Sports</a>
            <a class="dropdown-item" href="/events/?subcat=atheletics">Atheletics</a>
            <a class="dropdown-item" href="/events/?subcat=music">Music</a>
            <a class="dropdown-item" href="/events/?subcat=dance">Dance</a>
            <a class="dropdown-item" href="/events/?subcat=informals">Informals</a>
            <a class="dropdown-item" href="/events/?subcat=literary">Literary</a>
            <a class="dropdown-item" href="/events/?subcat=deco">Deco</a>
            <a class="dropdown-item" href="/events/?subcat=drama">Drama</a>
          </div>
        </div>
        <input type="text" name="q" placeholder="Search your event..." class="form-control" aria-label="Serach Event">
        <div class="input-group-append">
          <button type="submit" class="btn btn-outline-info" type="button"><i class="fa fa-search"></i></button>
        </div>
      </div>
    </form>
  </div>
	<table class="table text-center mt-4 border table-striped">
		<thead class="thead-dark table-striped">
    		<th>Title</th>
        <th>Gender</th>
    		<th>Category</th>
        <th>SubCategory</th>
        <th>Action</th>
        <th>Delete</th>
  	</thead>
  	{% for event in events.items %}
	  		<tr>
	    		<td><a href="{{url_for('event.event_page', eid=event.id)}}">{{event.title}}</a>
            {% if event.status %}
              <span class="badge float-right  badge-success">Online</span>
            {% else %}
              <span class="badge float-right badge-danger">Offline</span>
            {% endif %}
          </td>

          {% if event.gender == 'M' %}
            <td>Boys</td>
          {% elif event.gender == 'F' %}
            <td>Girls</td>
          {% else %}
            <td>Both</td>
          {% endif %}
	    		<td>{{ event.getCategory() }}</td>
          <td>{{ event.subcategory }}</td>
          <td>
            <a href="{{url_for('admin.update_event', eid=event.id)}}" target="_blank" class='btn btn-outline-info'>Update</a>
          </td>
          <td>
            <a href="{{ url_for('admin.delete_event', eid=event.id) }}" class='btn btn-outline-danger ml-3 rounded-circle'>✘</a>
          </td>
	  		</tr>
    {% endfor %}
  	</table>
    <nav>
    <ul class="pagination justify-content-center">
    {% for page_num in events.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}

      {% if page_num %}
        {% if events.page == page_num %}
          <li class="page-item active"><a class="page-link" href="{{ url_for('admin.AdminEvents', page=page_num) }}">{{ page_num }}</a></li>
        {% else %}
          {% if page_num == 1 %}
            <li class="page-item"><a class="page-link" href="{{ url_for('admin.AdminEvents', page=page_num) }}">First</a></li>
          {% elif page_num == last_page %}
            <li class="page-item"><a class="page-link" href="{{ url_for('admin.AdminEvents', page=page_num) }}">Last</a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="{{ url_for('admin.AdminEvents', page=page_num) }}">{{page_num}}</a></li>
          {% endif %}
        {% endif %}
      {% endif %}

    {% endfor %}
    </ul>
  </nav>
</div>
{% endblock %}

zestpkg/templates/AdminPannel.html
{% extends 'layout.html' %}
{% block content %}
<div class="text-center mt-4 animated bounceInDown">
	<h1>Admin Panel</h1>
	<h6 class="text-muted">with great power comes great responsibility</h6>
	<hr>
</div>
<div class="row justify-content-center mt-4 text-center">
	<div class="card" style="width: 18rem;">
	  <div class="card-body">
	    <h5 class="card-title mb-4">Zest2019 Database</h5>
	 <ul class="list-group">
	  <li class="list-group-item"><a href="{{ url_for('admin.AdminUsers')}}">User</a> ({{ user }})</li>
	  <li class="list-group-item"><a href="{{ url_for('admin.AdminEvents')}}">Event</a> ({{ event }})</li>
	  <li class="list-group-item"><a href="{{ url_for('admin.AdminTeams')}}">Team</a> ({{ team }})</li>
	  <li class="list-group-item"><a href="{{ url_for('admin.AdminContestants')}}">Contestant</a> ({{ contestant }})</li>
	</ul>
	  </div>
	</div>
	
</div>
{% endblock%}

zestpkg/templates/AdminUsers.html
{% extends 'layout.html' %}
{% block content %}
<div class="col-12">

  <div class="text-center mt-4 animated bounceInDown">
    <h2>User Table</h2>
    <hr>
  </div>
  <div class="row justify-content-center m-3 p-3">
    <form action="" method="GET">
      <div class="input-group m-3"> 
        <input type="text" name="q" placeholder="Enter username..." class="form-control" aria-label="Serach Event">
        <div class="input-group-append">
          <button type="submit" class="btn btn-outline-info" type="button"><i class="fa fa-search"></i></button>
        </div>
      </div>  
    </form>
  </div>
	<table class="table text-center mt-4 border table-striped">
		<thead class="thead-dark table-striped">
    		<th>PID</th>
    		<th>Name</th>
    		<th>E-Mail</th>
    		<th>Verify</th>
        <th>Delete</th>
  	</thead>

  	{% for user in users.items %}	
        {% if user.profile %}
	  		  <tr>
        {% else %}
          <tr class="table-danger">
        {% endif %}
	  			<td>{{user.id}}</td>
	    		<td>
            {% if user.profile %}
              <a href="{{url_for('profile.profile_card', username=user.username)}}">{{user.profile.name}}</a>
            {% else %}
              <a href="{{url_for('profile.profile_card', username=user.username)}}">{{ user.username }}</a>
            {% endif %}
          </td>
	    		<td>{{user.email}}</td>
	    		<td>
            {% if user.verified %}
              <a class='btn btn-success' onclick="return confirm('Are you sure?')" href="{{url_for('admin.toggleVerfiy', username=user.username)}}">✔️</a> 
            {% else %}          
              <a class='btn btn-secondary' onclick="return confirm('Are you sure?')" href="{{url_for('admin.toggleVerfiy', username=user.username)}}">✔️</a>
            {% endif %}
          </td>
          <td>
            <a href="{{ url_for('admin.delete_account', uid=user.id) }}" onclick="return confirm('Are you sure with deleting {{ user.username }}'s' account?')" class='btn btn-outline-danger ml-3 rounded-circle'>✘</a>
          </td>
	  		</tr>
    {% endfor %}
  	</table>
    <nav>
      <ul class="pagination justify-content-center">
      {% for page_num in users.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
        {% if page_num %}
          {% if users.page == page_num %}
            <li class="page-item active"><a class="page-link" href="{{ url_for('admin.AdminUsers', page=page_num) }}">  {{ page_num }}</a></li>
          {% else %}
            {% if page_num == 1 %}
              <li class="page-item"><a class="page-link" href="{{ url_for('admin.AdminUsers', page=page_num) }}">First</a></li>
            {% elif page_num == last_page %}
              <li class="page-item"><a class="page-link" href="{{ url_for('admin.AdminUsers', page=page_num) }}">Last</a></li>
            {% else %} 
              <li class="page-item"><a class="page-link" href="{{ url_for('admin.AdminUsers', page=page_num) }}">{{ page_num }}</a></li>
            {% endif %}
          {% endif %}
        {% endif %}
      {% endfor %}
      </ul>
    </nav>
</div>
{% endblock %}

zestpkg/templates/myevents.html
{% extends 'layout.html' %}
{% block content %}
<div class="text-center mt-4 animated bounceInDown">
	<h2>{{ title }}</h2>
	<hr>
</div>
<div class="row justify-content-around">

	{% if participations %}
	   	<table class="table text-center" >
		  <thead class="thead-dark">
		    <tr>
		      <th scope="col">Event</th>
		      <th scope="col">Team</th>
		      <th scope="col">Withdraw</th>
		    </tr>
		  </thead>
		  <tbody>
		  	{% for p in participations %}
			    <tr>
			      <td><a href="{{ url_for('event.event_page', eid=p.event.id) }}">{{ p.event.title }}</td>
			      {% if p.team %}
			      	<td>
			      		<a href="{{ url_for('team.team_card', tid=p.team.id) }}">{{ p.team.name }}</a> (TID: {{ p.team.id }})
			      	</td>
			      {% else %}
			      	<td>-</td>
			      {% endif %}

			      <td>
			      	{% if p.event.status %}
			      		<a href="{{ url_for('contestant.withdraw', eid=p.event.id) }}" onclick="return confirm('After this you will no longer be participant of {{ p.event.title }} event?')" class='btn btn-outline-danger ml-3 rounded-circle'>✘</a>
			      	{% else %}
			      		<button type="button" class="btn btn-outline-danger ml-3 rounded-circle" data-toggle="popover" title="Oops you can't!" data-content="Event registeration is closed right now, don't run away!">✘</button>
			      	{% endif %}
			      </td>
			    </tr>
			{% endfor %}
		   
		  </tbody>
		</table> 
	{% else %}
	<div class="container text-center">
		<img class="img-thumbnail m-2 emptymyevents" src="https://cdn.dribbble.com/users/24885/screenshots/1797793/events-empty-data-set_1x.png"><br>		
		<a class="btn btn-primary m-2" href="{{ url_for('event.all_events') }}">Browse Events</a>
	</div>
	{% endif %}
</div>
{% endblock%}

zestpkg/templates/participants.html
{% extends 'layout.html' %}
{% block content %}
<script>
  function printpage() {
    window.print();
  }
</script>
<style type="text/css">
  body
  {
      counter-reset: Serial;           /* Set the Serial counter to 0 */
  }

  table
  {
      border-collapse: separate;
  }

  tr td:first-child:before
  {
    counter-increment: Serial;      /* Increment the Serial counter */
    content: counter(Serial); /* Display the counter */
  }
</style>
<div class="text-center mt-4 animated bounceInDown">
	<h3 class="">{{ event.title }} 
    {% if event.gender == 'M' %}
      <small class="text-muted">for boys only</small>
    {% elif event.gender == 'F' %}
      <small class="text-muted">for girls only</small>
    {% else %}
      <small class="text-muted">for boys & girls both</small>
    {% endif %}
  </h3>
  <a href="{{ url_for('event.generate_excel', eid=event.id) }}">Download List</a>
	<hr>
</div>
<table class="table text-uppercase">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">PID</th>
      <th scope="col">NAME</th>
      <th scope="col">COURSE</th>
      <th scope="col">ROLL NUMBER</th>
      <th scope="col">COLLEGE</th>
    </tr>
  </thead>
  <tbody>
  	{% for contestant in contestants%}
    <tr>
      <td></td>
      <td scope="row" class="text-danger">{{ contestant.id }}</td>
      <td><a href="{{ url_for('profile.profile_card', username=contestant.username) }}">{{ contestant.profile.name }}</a></td>
      <td>{{ contestant.profile.course }}</td>
      <td>{{ contestant.profile.roll_number }}</td>
      <td>{{ contestant.profile.college }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock%}